### ISSUE TITLE
Add an admin-friendly way to recalculate rollups on an object

### ISSUE THREAD

**Issue by jongpie** [jamessimone/apex-rollup#14]
In the event that new rollups are added to an object, or existing rollup criteria is updated, existing data in orgs will need to be fully recalculated to ensure that the data is accurate. There should be an easy way for admins (and developers) to be able to select a object from the org's schema & run a batch job to recalculate all rollups for the selected object.

- User can select 1 object from the org's schema
- User can optionally provide criteria to filter the records that are included in the recalculation
- User clicks a button & a batch Apex job is initiated - the job should recalculated all relevant rollups for the select object

**Comment by jamessimone** [comment]
Broke ground on support for this last night/this morning. My initial thought on the subject of Batch Apex: `Rollup` already knows when to batch/queue based on the number of objects present - with a little bit of work, it will be possible to refine the existing scalability to make room for this full recalculation feature.

- count the number of calculation items that will need to be processed, total (remains to be seen if the criteria to filter records will be included in the MVP for this; could do this here and then extend it to #15 , or vice versa)
- if the count is close to the 50k query limit, use a batch class to gather all of the calculation items up prior to beginning to rollup; in other words, chain the new batch job into the existing infrastructure
- if the count is below and not close to the 50k query limit, gather the calc items _in-situ_ and begin the rollup process normally
- expose a LWC via a Lightning App via a new Tab that allows an admin to kick off the whole process!
- include Permission Set to add this new Tab's visibility

**Comment by jongpie** [comment]
That sounds amazing! Looking forward to seeing the changes in action

**Comment by jamessimone** [comment]
@jongpie just finished [the backend piece of this](https://github.com/jamessimone/apex-rollup/blob/v1.0.8/rollup/main/default/classes/RollupFullBatchRecalculator.cls), after a hilarious setback at the end of last night - turns out you can't have an inner class extend the functionality of the parent class's Batchable methods. Calling `Database.executeBatch` on an inner class instance leads to a gack, or "Internal Salesforce Error".

I thought you might be interested to see the above class and [the full recalculation method](https://github.com/jamessimone/apex-rollup/blob/v1.0.8/rollup/main/default/classes/Rollup.cls#L381) - ~30 lines of method code plus the class with the overrides.

Hope to wrap up the frontend pieces of this today/tomorrow and get v1.0.8 out there!

**Comment by solo-1234** [comment]
Did the front-end of this ever happen? I can refresh rollups via anon apex but it would be neat to be able to do it via the UI!

**Comment by jamessimone** [comment]
@solo-1234 yes! There is a button you can add via the “custom” section in the Lightning App builder for flexipages. You can refresh the CMDT rollups for any parent record using the button

**Comment by solo-1234** [comment]
That works great - thanks!

**Comment by jamessimone** [comment]
Great!
