### ISSUE TITLE
Rollup throws NullPointerException for DML in asynch context

### ISSUE THREAD

**Issue by fentes** [jamessimone/apex-rollup#167]
Hey James,

we use your rollup framework in multiple places in our org. The Rollup is embedded in a Trigger and is working as expected.

In one scenario, we create/update records in a batch job which is therefore asynchronous. Here the rollup fails, because of a NullPointer.

```
15:32:24.25 (5480334204)|EXCEPTION_THROWN|[335]|System.DmlException: Update failed. First exception on row 0 with id a0K1v00000PUGuhEAH; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, msContractTrigger: execution of AfterUpdate

caused by: System.NullPointerException: Attempt to de-reference a null object

Class.RollupAsyncProcessor.runCalc: line 283, column 1
Class.Rollup.runFromTrigger: line 1283, column 1
Class.msContractHandler.bulkAfter: line 61, column 1
Class.TriggerFactory.execute: line 64, column 1
Class.TriggerFactory.executeTriggerHandlers: line 18, column 1
Trigger.msContractTrigger: line 2, column 1: []
```
As far as I understood the code, you are trying to get an async instance of the class. Could it be possible, that rollups are not possible if the DML was done in an async context?

**Comment by jamessimone** [comment]
@fentes what version are you running? The current line 283 of `RollupAsyncProcessor`, for example, deals with logging - which would not have a NPE. It's possible that if you're running an earlier version, this issue has already been fixed as there were some ambiguities with which version of rollup would be used in an async context in some prior versions.

I have several other orgs (that I know of) calling rollup from within a batch job, so I know this should work. Any and all other details you can provide would be very beneficial!

**Comment by dschibster** [comment]
@fentes is a colleague of mine and we have just upgraded to 1.3.2 and the problem persists. It's in the runCalc() call where this.getAsyncRollup() is called - that one seems to be returning null, as otherwise we wouldn't be getting a Null Pointer in that line.

**Comment by fentes** [comment]
Hey James,

yeah we updated the framework in the meantime. The issue persists, but now with a

**Comment by dschibster** [comment]
Overriding the Standard Run behavior seems like a good deal to me. We did try setting Org_Defaults (the Control that was assigned) to Synchronous to no avail however.

**Comment by dschibster** [comment]
```
Message
rollup failed to re-queue for:

Stack Trace
Class.RollupNebulaLoggerAdapter.log: line 4, column 1
Class.RollupNebulaLoggerAdapter.log: line 9, column 1
Class.RollupAsyncProcessor.logFatalRollups: line 651, column 1
Class.RollupAsyncProcessor.getAsyncRollup: line 318, column 1
Class.RollupAsyncProcessor.runCalc: line 283, column 1
Class.Rollup.runFromTrigger: line 1283, column 1
Class.msContractHandler.bulkAfter: line 61, column 1
Class.TriggerFactory.execute: line 64, column 1
Class.TriggerFactory.executeTriggerHandlers: line 18, column 1
Trigger.msContractTrigger: line 2, column 1
```

This is all logFatalRollups is giving us. There is currently a Rollup in place for the Object in question, but it's gatekept with a Changed Field that is not changed within this async call.

**Comment by jamessimone** [comment]
@dschibster if updating the rollup control didn't work, then you're already past the limits for what rollup deems acceptable for a sync run, which is a combo of the following:

- number of queries issued (compares to the `MaxNumberOfQueries__c` field on Rollup Control)
- number of query rows currently retrieved in any given context (compares to `MaxLookupRowsBeforeBatching__c` field on Rollup Control)
- heap size (if you're over half the available heap size; this value is currently hardcoded in `Rollup.hasExceededCurrentRollupLimits()`
- number of DML rows (compares to `MaxParentRowsUpdatedAtOnce__c` field on Rollup Control)

So ... that leaves us in a bit of a pickle. I could simply say "hey, if they provide the override, don't check the limits - they know what they're doing" 

Interesting about the stacktrace you just posted. That means I may have a bug above the call to `getAsyncRollup` - the line that's currently 274 is probably bugged since the `&& this.calcItems?.isEmpty() == true` could evaluate `this.isNoOp` to false even if, as you said, none of the items match.

**Comment by jamessimone** [comment]
@fentes @dschibster knowing that this process should be gatekept with the changed fields, I think I have enough info to fix this issue for you two at the very least. I have one other user in Japan that is probably running into a similar issue to what you're reporting though, so even if I fix this for you two in `v1.3.3`, I'll probably have to get a failing test for the exact situation you're describing so that I can work on a more reliable fix down the line.

**Comment by dschibster** [comment]
First of all I really appreciate you being so responsive here! It would be great if the Changed Fields made a difference here. However, looking at the Limits from Nebula Logger:

![image](https://user-images.githubusercontent.com/34553908/134036676-7c6a493d-fcd4-44b3-bd57-b2442f1eced9.png)

I don't seem to find any limit exceeded here.

The Setup is a Rollup to the ultimate Parent based on a WHERE Condition and one specific field that is rolled up and the record should then, of course, only be considered when this specific field changes. 

Because of other problems relating to the Objects in question the insert/update process that we are triggering is done via Batchable Apex. Within this, this is the third DML Statement. The only change is one field that has nothing to do with the Rollup. THe other two Objects do not have a Rollup created currently, neither do I know of any Queueables that are fired as part of their Triggers.

**Comment by dschibster** [comment]
One other fun fact: When we switch the Org Control to Synchronous, we are still getting a null-pointer but the logFatalRollups() method does not seem to get called.

![image](https://user-images.githubusercontent.com/34553908/134038603-4822eb66-a31b-48a6-a6b0-e0f10f83d182.png)

**Comment by jamessimone** [comment]
@dschibster that `Async Calls 1/1` is interesting in the first pictured log - that honestly makes me believe that rollup is being invoked twice in the same batch class - could that be happening? That theory would seem to be confirmed since the sync one shows 0/1. Are you doing this in a sandbox, by chance? I could push up a beta package for you to test.

**Comment by dschibster** [comment]
This is currently happening on our Full Copy, so a beta package could be installed without much disturbance. The Framework currently in use is the sfdx-trigger-factory repo on my account with slight adjustments, and in order to accomodate the framework Rollup.runFromTrigger() is called once in bulkBefore() and once in bulkAfter(). 

That's pre-processing methods that are called once in each Before/After Context. in this case Rollup would be called once in BEFORE_UPDATE and once in AFTER_UPDATE, if that is of any help here. If this needs to be limited certain contexts per BEFORE/AFTER call, we can certainly do that.

That certainly IS a nice find though! We were actually planning to include Rollup.runFromTrigger() as a general method before Handlers are called in order to make Rollups plug-and-play even moreso than before. 😅

**Comment by jamessimone** [comment]
@dschibster and @fentes - this is why we owe @jongpie so much for having contributed Nebula Logger to the community!

Beta package created - let's give this a roll with `https://test.salesforce.com/packaging/installPackage.apexp?p0=04t6g000008ShbYAAS` or just using package Id `04t6g000008ShbYAAS` if you're installing through sfdx.

**Comment by jongpie** [comment]
Not to distract from the issue at hand here, but just wanted to say it's awesome seeing Apex Rollup and Nebula Logger working together! ❤️

**Comment by dschibster** [comment]
Two of the best open-source tools I've come across, so big thanks to both of you, really. :)

**Comment by fentes** [comment]
@jamessimone you are totally awesome! Thank you very much for this incredibly fast fix. We installed it, and now it works also in batch mode.

And yeah, both tools are a huge benefit for us. For both tools, we have an old custom-built solution, which isn't scalable or does not serve our needs anymore. But with Nebula/Rollup, we are able to remove the old code and tidy up the whole org.

**Comment by jamessimone** [comment]
(as an aside - how soon do you need the fix in production? I can promote this beta package version later today if it's urgent; otherwise, I may try to do a little more tweaking on other sections of the codebase prior to releasing `v1.3.3` for real)

**Comment by dschibster** [comment]
Say, @jamessimone, do you think it makes sense to generally include runFromTrigger() in order to account for any future trigger without the need to manually include it in every Trigger Handler? Or would it cause problems down the line when multiples are called within the same execution?

**Comment by jamessimone** [comment]
@dschibster so in your `TriggerFactory` you would be adding that call into the `andFinally()` method? 

Theoretically at least, it's possible for recursive updates to be valid instances where rolling up would need to be done again, and I try to already handle bailing early out of a recursive update on the same SObject if none of the values related to the rollup have changed, but yes - in general, if you have a consistent place in your trigger framework to use the one-liner from, that will be the best approach!

**Comment by dschibster** [comment]
Actually, I'm planning to include it in `executeTriggerHandlers()` because then we don't have a potential dependency on multiple Handlers per Object, it can just run once and be done! But thanks for confirming that.

**Comment by jamessimone** [comment]
@dschibster @fentes you should be all set with the latest version - which will be promoted momentarily. My best!
