### ISSUE TITLE
Deployment fails with invalid type error

### ISSUE THREAD

**Issue by feisley** [jamessimone/apex-rollup#17]
When attempting to deploy to Salesforce we encountered the following errors:

Invalid type: ContactPointAddress
Invalid type: ContactPointEmail

This appears to be due to the fact that we do not have 'Person Accounts' enabled in our org and this field comes from there.

There are a number of related errors all coming from the 'RollupTests' class for fields related to these two types.

**Comment by jamessimone** [comment]
Ah, the fallacy of having written the time-field tests in a Dev Ed org. I will fix this immediately. Give me a few minutes!

**Comment by jamessimone** [comment]
@feisley this should be addressed in the latest update to master. Please confirm, and feel free to reopen in the event that there's any issue. Thanks for reporting, I appreciate it - enjoy your time with `Rollup`!

**Comment by feisley** [comment]
Deployment was good.

Looking forward to diving into this tool, awesome work!

**Comment by jamessimone** [comment]
@feisley digging back into this, today, to hopefully find a long-term solution for this issue (instead of what I did to address it last night, which was moving the tests referencing `ContactPointAddress` and `ContactPointEmail` to a folder that isn't referenced in what gets deployed with `Rollup`.

Can you describe your org in a bit more detail for me? I just checked in multiple orgs across a variety of different environments, and verified that even in orgs with person accounts disabled, those objects show up and are available. The documentation surrounding ContactPointEmail/Address, while sparse, says that they're available in API versions 48.0 and later - which should be pretty much everything, at this point.

Out of curiosity, as well, can you run this snippet in Anonymous Apex to see if there's _anything_ that is reported as a valid Time field on standard objects in your org?

```java
public static void printDisplayTypeInfo(DisplayType desiredType) {
  Map<String, SObjectType> namesToTypes = Schema.getGlobalDescribe();
  for(SObjectType sType : namesToTypes.values()) {
    Map<String, SObjectField> fields = sType.getDescribe().fields.getMap();
    for(String fieldName : fields.keyset()){
      SObjectField field = fields.get(fieldName);
      DescribeFieldResult describeResult = field.getDescribe();
      if(describeResult.getType() == desiredType && describeResult.isUpdateable()) {
          System.debug('SObjectType: ' + sType);
          System.debug(describeResult.getName());
      }
    }
  }
}

printDisplayTypeInfo(Schema.DisplayType.TIME);
```

Thank you! I very much appreciate any additional insight you can bring to light about this for me.

**Comment by feisley** [comment]
@jamessimone I was deploying this using the 'Deploy to Salesforce' button on the Github repo this was being deployed to one of our main testing sandboxes. The only unique thing about this sandbox is that due to some integrations we have with it, it has not been 'refreshed' in 3 - 4 years. (Though configuration is kept up to date with production via change sets or metadata deployments)

I checked in Workbench and interestingly in sandbox the 'ContactPointAddress' and 'ContactPointEmail' objects are not shown, however if I sign into production with Workbench then both of those objects are visible.

When I ran the anonymous Apex in the sandbox in question, I saw results from the BusinessHours object for the start and end time of each day of the week. When run in production I saw the same **plus** fields on the 'ContactPointAddress' and 'ContactPointEmail' objects.

**Comment by jamessimone** [comment]
@feisley that all makes sense. I didn't know that sandboxes could _stop_ being refreshed; even very old ones that I have eventually get the latest release, but there's no way your prod org wouldn't have those objects as they've been available for two releases now. The original tests I had written for the `Time` components of `Rollup` did indeed use the BusinessHours object, but it was a bit hacky because DML is not allowed on that object. I'll have to mull this one over. 

In the future, if your sandbox is still not updated and I haven't figured out a more amenable "spanning the versions" solution for testing `Time` components, you could still upgrade `Rollup` by taking the contents of the class and replacing what you have currently in the sandbox. Anyway, I very much appreciate your help with this!

**Comment by feisley** [comment]
@jamessimone ok some notes and discoveries: First when i said the sandbox had not been refreshed, I meant metadata/config replaced from production. It is still receiving version upgrades (in fact its already on Spring 21 so it has all the newest features)

In my searching for why the objects might not be appearing i came across https://salesforce.stackexchange.com/questions/294719/no-layout-named-contactpointemail-contact-point-email-layout-found-spring20-sa

While not my exact situation, they pointed out that there was a need to run the License Match process on the sandbox as some features were technically behind 'licensing' that was applied to prod but not automatically replicated to sandboxes.

After running this on my sandbox, it now has those objects in it. (Yay)

**Comment by jamessimone** [comment]
@feisley this is great news! I was really stumped trying to figure out how your sandbox hadn’t been upgraded; I even had a colleague reach out to people at Salesforce to try to figure this out. What you said makes more sense, and provides hope that there is an upgrade path for any sandbox that is in a similar state. Thanks so much for your due diligence!
