### ISSUE TITLE
Using two Logger Plugins (Apex + Nebula) skips at least one of them and doesn't account for the LoggingLevel of the other

### ISSUE THREAD

**Issue by dschibster** [jamessimone/apex-rollup#171]
Hi @jamessimone, here's the issue I talked about

I was facing this issue in the previous version of the Plugin Framework already, and was only able to get rid of it by using a "disabled" Rollup Control for one or the other, but having both of them assigned to Org_Default didn't give me a log from Nebula Logger. 

Right now when I have both Plugins in Place, I see the following log when I try to Replay Debug it:

```
21:50:15.0 (971761613)|VARIABLE_SCOPE_BEGIN|[41]|this|RollupLogger|true|false
21:50:15.0 (971820177)|VARIABLE_ASSIGNMENT|[41]|this|{"currentLoggingLevel":"0x42d25100","loggingLevelPluginParameter":"0x7a407a61","invokePoint":"0x322308f6","isCDCUpdate":false,"isConductor":true,"isFullRecalc":false,"isNoOp":true,"rollupControl":"0x1c8198e0"}|0x726eeb9f
21:50:15.0 (971829840)|VARIABLE_SCOPE_BEGIN|[41]|logString|String|false|false
21:50:15.0 (971842624)|VARIABLE_ASSIGNMENT|[41]|logString|"about to start for R (38 more) ..."
21:50:15.0 (971849097)|VARIABLE_SCOPE_BEGIN|[41]|logLevel|System.LoggingLevel|true|false
21:50:15.0 (971865417)|VARIABLE_ASSIGNMENT|[41]|logLevel|"DEBUG"|0x1db690de
21:50:15.0 (971879186)|HEAP_ALLOCATE|[42]|Bytes:5
21:50:15.0 (971885241)|STATEMENT_EXECUTE|[41]
21:50:15.0 (971887922)|STATEMENT_EXECUTE|[42]
21:50:15.0 (971899583)|METHOD_ENTRY|[42]|01p9E000002rbrX|RollupLogger.log(String, Object, System.LoggingLevel)
21:50:15.0 (971917534)|VARIABLE_SCOPE_BEGIN|[46]|this|RollupLogger|true|false
21:50:15.0 (971978170)|VARIABLE_ASSIGNMENT|[46]|this|{"currentLoggingLevel":"0x42d25100","loggingLevelPluginParameter":"0x7a407a61","invokePoint":"0x322308f6","isCDCUpdate":false,"isConductor":true,"isFullRecalc":false,"isNoOp":true,"rollupControl":"0x1c8198e0"}|0x726eeb9f
21:50:15.0 (971990593)|VARIABLE_SCOPE_BEGIN|[46]|logString|String|false|false
21:50:15.0 (972006319)|VARIABLE_ASSIGNMENT|[46]|logString|"about to start for R (38 more) ..."
21:50:15.0 (972016440)|VARIABLE_SCOPE_BEGIN|[46]|logObject|Object|false|false
21:50:15.0 (972029180)|VARIABLE_ASSIGNMENT|[46]|logObject|null
21:50:15.0 (972036478)|VARIABLE_SCOPE_BEGIN|[46]|logLevel|System.LoggingLevel|true|false
21:50:15.0 (972054760)|VARIABLE_ASSIGNMENT|[46]|logLevel|"DEBUG"|0x1db690de
```

Which seems strange to me, because I switched the LoggingLevel to FINEST in the Parameter, but both calls of log() are using logLevel DEBUG.

Previously, I was receiving a graceful exception (it was swallowed somewhere inside Rollup and let me execute on) inside `combineLoggers()`. I think it was a NPE, or a TypeException (even after making sure I typed the name correctly), but I can't reproduce this in my current setup, I don't get deep enough inside the package code to do that unfortunately. 

Testament to that problem is that I have Logging enabled in my setting currently, but Nebula Logger is not creating new Logs or LogEntries. Deleting the Apex Logger does however let me get Nebula logs.

Not sure if adding some more debug statements inside the logging methods may provide additional info? What do you reckon?

**Comment by jamessimone** [comment]
@dschibster so I think there's a point to clarify here - the way the `RollupPluginParameter.LoggingDebugLevel` record works is this: if the logging level that you input there meets or exceeds your current Apex debug logging level, you'll _see_ the logs that are configured to be output at that logging level in your Apex debug logs. So in the case of the example you posted, that specific logging line uses `DEBUG` as the hard-coded logging level - and because you have `FINEST` in the corresponding parameter (which should be linked to the `RollupLogger` via the `RollupPluginParameter__mdt.RollupPlugin__c` lookup field), since FINEST is more granular than DEBUG, you should get all logs configured in `apex-rollup` up to and including `FINEST` (which amounts to `ERROR`, `WARN`, `DEBUG`, `FINE`, `FINER` and `FINEST`, exhaustively).

This differs from the behavior of the Nebula Logger adapter, which simply passes the `LoggingLevel` _to_ Nebula.

The update to 1.3.0 _should_ have stabilized the logging plugin framework. Do you also have the `Is Rollup Logging Enabled` checkbox checked off on the `Org_Default` Rollup Control? The built in logger respects that checkbox; the Nebula Adapter does not (since Nebula has its own controls for turning logging on and off).

I'm eager to ensure that the [Wiki article I wrote on logging](https://github.com/jamessimone/apex-rollup/wiki/Debugging-Using-The-Apex-Rollup-Logger) encapsulates everything necessary to _use_ the debug logging, so if there's something missing there or in any of the READMEs, please let me know!

**Comment by dschibster** [comment]
It is currently checked, I doubly made sure. To that effect, no logs show up. I haven't isolated User Debug with both MDTs in place but I can ensure that Nebula did not run, otherwise my last log wouldn't have been created at 5.30pm.

Thanks for the clarification regarding log levels, I guess that the developer console did a number on my assigned log levels there. Nevertheless this doesn't explain why the second Plugin isn't doing anything...

**Comment by jamessimone** [comment]
@dschibster what is the name of the `RollupPlugin__mdt` record you have for Nebula? Just want to ensure you have the `RollupPlugin.RollupNebulaLoggerAdapter` record showing up there as expected (and you're using `0.0.3` for the Adapter plugin)?

I was able to successfully test on my end that all three loggers ran without issue, but if there's some issue with Nebula I'm wondering if on your `LoggerSettings__c` custom setting if the `Generate Debug Statements` checkbox is enabled, since Nebula might then spit out some additional info (assuming that the adapter was even being properly called). We will get to the bottom of this!

**Comment by dschibster** [comment]
![image](https://user-images.githubusercontent.com/34553908/134466763-944bc2e2-7d9f-4f35-91fe-c6a6a5f255b8.png)
The RollupPlugin records are completely standard, just the way they are after installation.

Does Nebula Logger require a certain version too? We were using a customization in the Logger class and are a little wary about upgrading + altering again. It did work with the current version just as long as I don't have a second CMDT though. Cerainly strange.

![image](https://user-images.githubusercontent.com/34553908/134467129-3d5efe94-8acf-49ff-8503-22b3ee4d5ddf.png)

`LoggerSettings__c` also don't seem to be too problematic to me.

**Comment by jamessimone** [comment]
@dschibster at `FINER` or `FINEST` debug levels for the `Logging Debug Level` rollup plugin parameter CMDT, the first line in any log should be info about the retrieved logging plugins (for example - this is with the Nebula Logger plugin removed):

```
09:22:20.268 (892884848)|USER_DEBUG|[63]|FINE|Rollup: retrieved the following logging plugins:
[ {
  "attributes" : {
    "type" : "RollupPlugin__mdt",
    "url" : "/services/data/v52.0/sobjects/RollupPlugin__mdt/m0I6g000000EzZ1EAK"
  },
  "DeveloperName" : "RollupCustomObjectLogger",
  "Id" : "m0I6g000000EzZ1EAK"
}, {
  "attributes" : {
    "type" : "RollupPlugin__mdt",
    "url" : "/services/data/v52.0/sobjects/RollupPlugin__mdt/m0I6g000000EzYwEAK"
  },
  "DeveloperName" : "RollupLogger",
  "Id" : "m0I6g000000EzYwEAK"
} ]
Class.RollupLogger.getRollupLogger: line 132, column 1
Class.RollupLogger.__sfdc_Instance: line 28, column 1
Class.RollupAsyncProcessor.beginAsyncRollup: line 436, column 1
Class.RollupAsyncProcessor.runCalc: line 293, column 1
Class.Rollup.runFromTrigger: line 1341, column 1
Class.RollupIntegrationTests.shouldWorkUsingCustomFieldWithCmdt: line 49, column 1
```

Just want to ensure that the Nebula Logger adapter _is_ showing up there for you, first, before trying to diagnose further.

**Comment by dschibster** [comment]
```
19:00:41.101 (1212109727)|USER_DEBUG|[63]|FINE|Rollup: retrieved the following logging plugins:
[ {
  "attributes" : {
    "type" : "RollupPlugin__mdt",
    "url" : "/services/data/v53.0/sobjects/RollupPlugin__mdt/m0i9E0000004G7kQAE"
  },
  "DeveloperName" : "RollupLogger",
  "Id" : "m0i9E0000004G7kQAE"
}, {
  "attributes" : {
    "type" : "RollupPlugin__mdt",
    "url" : "/services/data/v53.0/sobjects/RollupPlugin__mdt/m0i9E0000004G76QAE"
  },
  "DeveloperName" : "RollupNebulaLoggerAdapter",
  "Id" : "m0i9E0000004G76QAE"
} ]
Class.RollupLogger.getRollupLogger: line 132, column 1
Class.RollupLogger.__sfdc_Instance: line 28, column 1
Class.RollupAsyncProcessor.beginAsyncRollup: line 436, column 1
Class.RollupAsyncProcessor.runCalc: line 293, column 1
Class.Rollup.runFromTrigger: line 1341, column 1
Class.TriggerFactory.executeTriggerHandlers: line 17, column 1
Trigger.msContractTrigger: line 2, column 1
```


I receie the log, but no Nebula Logger logs. :)

**Comment by jamessimone** [comment]
@dschibster I figured out the issue. Classic case of a misplaced bracket in `RollupLogger`. I'll be pushing up a fix for this shortly, just looking at some additional log-related things with @jongpie

**Comment by dschibster** [comment]
Awesome stuff. That would explain why it works as the first logger, but not in the CombinedLogger. Thanks a lot James!

**Comment by jamessimone** [comment]
@dschibster releasing this fix now! thanks again for reporting it
