### ISSUE TITLE
Rollup only to certain parent

### ISSUE THREAD

**Issue by fentes** [jamessimone/apex-rollup#173]
Hey @jamessimone,

like mentioned in #170, we want to rollup only to certain parent records. Our scenario is like the following (a bit simplified):

We have a custom object called "Contract__c". Contracts can have a hierarchy structure, via a lookup to the same object (Contract__c). The lookup field is called Parent_Contract__c.

What is working: filter child contracts and sum them up to their parent. For example sum up all blue contracts to their parent. To the parent should have the capacity 250:
![image](https://user-images.githubusercontent.com/29252948/134623140-59b58f16-8ed8-4264-88be-032f343cd131.png)
We would be able to achieve this by have a Calc Item Where Clause: `Color__c='blue`
![image](https://user-images.githubusercontent.com/29252948/134623694-d1335ab1-3c4c-49ec-94f8-4172260d5a41.png)

What we would like to achieve, is filtering on the parent contract level. For example, sum up **all** contracts to their parent contract, if the parent is yellow. For green parent contracts do nothing. So goal is, that the capacity on the green contract is 0 and on the yellow one 750:
![image](https://user-images.githubusercontent.com/29252948/134623340-8260f99c-a783-4c95-a759-a1f1d20a3a47.png)
To achieve this, our idea was to add the parent lookup field into the where clause: `Parent_Contract__r.Color__c='yellow'`
![image](https://user-images.githubusercontent.com/29252948/134623884-b997496d-57eb-40ba-949b-2f328cf5d269.png)
But in this case nothing will be rolled up. We don't get any error/log and the parent contracts won't be changed. We tried this in synch mode, by changing the "Active Capacity" field on our Contract__c.

**Comment by jamessimone** [comment]
@fentes thanks for the detailed images, they really help to understand what’s going on here. One thing I want to make sure of, given that last image - you have the where clause in the `Changed Fields on Calc Item` area. I’m assuming that was just a small mistake from assembling a sample image of the Rollup CMDT for me? It should be in the `Calc Item Where Clause` field below that one.

Also - the SOQL where clause parser I’ve built _requires_ spaces between each word, like such: `Parent_Contract__r.Color__c = ‘yellow’`. This is something I can probably do a better job of highlighting within the Readme/documentation. To be clear: I’m not suggesting that there isn’t still a problem here; I just want to check all the boxes on our way to determining what the issue is!

If the logging debug level for the included Rollup Plugin Parameter CMDT record is set to FINEST, information about how the calc item where clause is being considered gets printed out. Also, a “trick” several others use to get all the relevant info in one log is to write a unit test demonstrating the issue; that way, the Org Default Rollup Control doesn’t have to be set to sync and all of the info is still collated into one easily readable file. I am not saying that’s strictly necessary on your behalf (since the info you’ve given me has been extremely detailed, and it should be enough to go on), but I thought it worth mentioning here.

Lastly, I’m on the road today and this weekend, leaving me with somewhat limited time over the next few days. Worst case scenario if I’m not able to work on this, I would expect a fix (assuming the above steps don’t help!) early next week. Thank you!

**Comment by fentes** [comment]
Hey, good point with the spaces. I'm not sure if we had some. And you're right. It was a mistake while creating the Screenshots. Normally we use the correct field. I will create a test and a log for you. But it takes some time.  Don't worry about this issue. For now we found a workaround, so no hurry 😉

**Comment by fentes** [comment]
Hey @jamessimone, I created a test class and tried a bit with the where clause. 
Strange thing: the test seems to calculate wrong values. I create a Contract with a capacity of 100 and update the capacity afterward to 200. The related parent should them have a capacity of 200 (there is only one child). But the parent capacity is 400 🤨

After adding a where clause like:   Parent_Contract__r.Contract_Type__c = 'Bla Bla' 
nothing will be rolled up.

Find attached the logs (censored and simplified by removing validations, and other unrelated triggers/processes/flows/..) and the test class.

Is there anything else, I can help you with?

[log without where clause.txt](https://github.com/jamessimone/apex-rollup/files/7237097/log.without.where.clause.txt)
[log with where clause.txt](https://github.com/jamessimone/apex-rollup/files/7237099/log.with.where.clause.txt)
[ContractRollupTest.txt](https://github.com/jamessimone/apex-rollup/files/7237132/ContractRollupTest.txt)

**Comment by jamessimone** [comment]
@fentes apologies for the delay.

When I'm looking at the `log without where clause.txt` file you've uploaded, I am seeing a few things:

* there is an additional Contract being found with name `DE0167114` that is skewing the results
* it seems you have two separate entry points that are both calling `Rollup` at the same time - once in  `TriggerFactory.executeTriggerHandlers` and once in `msContractHandler.bulkBefore` (which is also called from `executeTriggerHandlers` from the looks of it) - by the time we get to the `UPDATE_SUM` sections of the log (log entries 77 & 80, respectively, if you're filtering on `USER_DEBUG`), there are two queued rollups with the same info in them
* I will continue to investigate the where clause issue, and this certainly helps

**Comment by jamessimone** [comment]
Side note - I was able to reproduce the parent filtering issue in a test. I am going to try out a few things as far as solutions go. My _ideal_ solution would be to append any parent-level where clauses to the parent queries when they are being performed; I was able to validate that if the calc items you're passing in _already have_ the parent-level values, the filtering works as expected. I was able to do this in a test by requerying the records after inserting them - not very realistic, of course.

The easiest thing to do would be to requery the calc items _in situ_ prior to doing any filtering at all, but I'll examine the feasibility of that approach versus adding the conditions to the query for retrieving parent-level items. Thanks for submitting this!

**Comment by fentes** [comment]
Hey,

we have an additional trigger that renames the contract name and therefore the contract DE0167114 is one of the created ones. The entry point is quite interesting. As Dennis mentioned, we moved the runFromTrigger() from the handler class into our trigger pattern, but as it seems we didn't delete it from the handler class. So seems to call the rollup twice, end up doubling the values.  
I removed the runFromTrigger() in the handler class and the results are fine now 😅.

To your approach: If you are able, to keep the parent clause in the child query, you might be able to filter children by a third object: This could be a different use case. For example:
The scenario is like described above: Rollup value from Contract__c (child) to Contract__c (parent). But now let's filter not on the parent but on Opportunity.

So roll up the amount of all children contracts where the linked opportunity is closed won, to the parent. A Where clause could look like: 
`Opportunity__r.Status= 'Closed Won'`

This is not a use case we have for now, but I think, this could be helpful for other users in general.

**Comment by jamessimone** [comment]
@fentes great point. That solidifies my approach, then - thanks for your input!

**Comment by jamessimone** [comment]
@fentes 👋 I haven't forgotten about you! Apologies for the delay in movement on this issue - I wanted to take the weekend to think about it, and when I broke ground on the issue I was glad for the time I'd spent contemplating it. There was already a section of code in `Rollup.cls` similar in functionality to what you were requesting, but geared specifically towards `Calc Item Where Clause`(s) with polymorphic parent filtering, and I wanted to expand upon that section carefully.

In examining that section of the code, and knowing that I'd have to add in something similar to deal with your request, it also became important to me to deal with some potential scaling concerns I had - since it would be necessary to re-query for calc items getting passed into the framework for either of these two cases, I wanted to give people configuration options when choosing how and when `apex-rollup` was going to be performing these queries. I also have users passing multiple thousands of calc items in at any given time, and adding two queries into the synchronous mix wasn't going to be doing anybody any favors there. 

This fix will add in `RollupControl__mdt.ReplaceCalcItemsAsyncWhenOverCount__c` (defaults to `1`), so if there are ever multiple calc items being processed, the replacement for any sort of parent-level where clauses will only ever happen async.  I am going to examine #179 to see what the issue is there, and if a fix will be necessary for that, but I will be looking to release `v1.3.7` by the end of the week for you. Thank you for your patience, and again for your extremely detailed summary on this issue!
