### ISSUE TITLE
System.IllegalArgumentException creeping up

### ISSUE THREAD

**Issue by rygramer** [jamessimone/apex-rollup#174]
Hey James, hope you're well! I see you've been jamming out with Apex Rollup - things are looking great. I especially enjoy the new Wiki. Thanks for all you're doing.

I recently had `System.IllegalArgumentException: Prior records to rollup collection required for rollup context: UPSERT` creep up in an org, and I can't figure it out. It's entirely possible this is user error.

Here's a quick video for context: https://share.vidyard.com/watch/XFHiP2Ndwg71RvVUA4m5AH?

**Comment by jamessimone** [comment]
@rygramer I’m well indeed, thanks for those weekend wishes! Any chance you could open up the Salesforce Dev Console while trying to do that problematic insert with your Rollup Control Org Default CMDT record’s `Is Rollup Logging Enabled` flag checked off? It looks like you have everything set up correctly, so the logging should be able to clarify what the issue is with Record_Prior (allegedly) not being passed to the rollup!

Once we have that info, diagnosing this should be a lot easier; if you open up the log that gets generated and filter for debug only,  the first (or second, depending on your logging level) message should be exactly what was passed into the flow.

Thank you!

**Comment by rygramer** [comment]
![Screen Shot 2021-09-24 at 4 46 16 PM](https://user-images.githubusercontent.com/4349178/134737755-84cb3747-6548-4b71-9725-b0d358421e5c.png)
Let me know if you need any additional info!

**Comment by jamessimone** [comment]
@rygramer alas. I do the validation prior to printing what gets passed to the flow (you should see where the print statement is on line 629 of `Rollup.cls`) - if it WERE possible to move that line up to before the line on 608 that calls the flow-specific validations, that would certainly help since the validation error message in this case isn’t entirely helpful, and seeing the contents of the passed in flow input would (hopefully) clarify things. Let me know if that’s feasible!

**Comment by rygramer** [comment]
Will do this weekend!

**Comment by rygramer** [comment]
[apex-07L780000008ueJEAQ.log](https://github.com/jamessimone/apex-rollup/files/7228801/apex-07L780000008ueJEAQ.log)
How's this? I set Debug Levels to only log Debugs in Apex

**Comment by rygramer** [comment]
Also, looks like the error is only being thrown when I have multiple CMDT rollup records per object. If I only have ONE rollup being performed, the record saves without issue.

**Comment by jamessimone** [comment]
@rygramer ok this is all good info! That log was indeed helpful. I’m hoping that the insights there, along with your note about the issue only being present with multiple CMDT records, will let me track down the underlying issue. I’m also meeting up with the TaskRay folks next week (completely coincidentally), I can always pester them about this 😅.

I really appreciate you taking the time out of your Friday to help me further document this issue; I’m traveling this weekend, so I can’t necessarily promise a weekend fix, but I will get to the bottom of this for you and I’ll do it in a timely fashion.

**Comment by jamessimone** [comment]
(just an update - I’ve tracked down where this issue is occurring; it should be a relatively simple fix)

**Comment by rygramer** [comment]
You're a legend. Apex Rollup is truly a joy.

**Comment by jamessimone** [comment]
@rygramer just pushed up a commit to address this issue, but I'll be offline the rest of the day and I'm hoping to get more info about #173 before publishing `v1.3.6`. To that end, I've [created a beta package for you](https://test.salesforce.com/packaging/installPackage.apexp?p0=04t6g000008ShmOAAS) in the event you want to upgrade any sandbox/scratch org you're working with.

Thanks again for reporting this issue, expect it sometime early next week!

**Comment by rygramer** [comment]
Thanks @jamessimone!
