### ISSUE TITLE
Recalculate Rollups button on Grandparent

### ISSUE THREAD

**Issue by rygramer** [jamessimone/apex-rollup#176]
Morning James. When using the `Recalculate Rollups` LWC button on a **Grandparent**,  the calculation isn't running properly.

From the debug log:
![Screen Shot 2021-09-27 at 9 52 35 AM](https://user-images.githubusercontent.com/4349178/134922226-18fec65c-04b4-4534-899e-5311dafed8b9.png)

`"CalcItemWhereClause__c" : " ||| Parent__c = 'a2978000000GmaTAAS'"` is what jumps out to me. `a2978000000GmaTAAS` is the Grandparent Id, not the Parent Id.

**Comment by jamessimone** [comment]
@rygramer ah yes. If you examine the **Special notes on the recalc button** section of the readme, you'll see the following:

- Triggering recalcs from a grandparent record for a grandparent rollup currently not supported

This is something I have been meaning to work on  - thank you for submitting this, as it's as good a reason as any to get things up and running for grandparent rollups with the full recalc button. I think I will merge and release `v1.3.6` with the fixes for #175 and #174 this morning, with the promise that the fix for this will be included in the next release.

**Comment by rygramer** [comment]
Ah, sorry I missed that man. I'd love to help cherry pick these issues with you, but, in the short term, your code base farrrrrr exceeds my Apex skills. I am but a humble student of the master.

**Comment by jamessimone** [comment]
Not to worry, and always happy to set up a paired programming session!

I also have on my short-term roadmap the creation of an architectural overview for `apex-rollup` - it's not a small project, by any means, and I know it's not the easiest thing to approach. The full recalculation section of the codebase happens to have some very specific unit tests (`RollupFullRecalcTests`), and sometimes just reading through the tests is the easiest way to get that overview in the absence of a guided tour.

**Comment by rygramer** [comment]
I would be so grateful for a paired programming session. I'll review `RollupFullRecalcTests`, which will prompt some questions and may be a good starting point to connect.
