### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by RomanTheCube** [jamessimone/apex-rollup#19]
Attempting to deploy from https://githubsfdeploy.herokuapp.com/app/githubdeploy/jamessimone/apex-rollup results in the following errors:

Status: Completed 
Deployment Complete

Test failure, method: RollupTests.shouldMaxDateOnInsert -- System.AssertException: Assertion Failed: Records should have been populated MAX DATE AFTER_INSERT: Expected: 1, Actual: 0 stack Class.RollupTests.shouldMaxDateOnInsert: line 1206, column 1

Test failure, method: RollupTests.shouldMinDateOnUpdate -- System.AssertException: Assertion Failed: Expected: 2020-12-06 00:00:00, Actual: 2021-01-30 00:00:00 stack Class.RollupTests.shouldMinDateOnUpdate: line 1278, column 1

**Comment by jamessimone** [comment]
Hey @RomanTheCube do you have an older version of `Rollup` installed, or is this a fresh installation? All feature branches and the master version of the code have all tests run on both a sandbox and a scratch org to validate the results prior to promoting releases, and neither of those tests is failing for me on a scratch org or sandbox (nor have they, since MIN/MAX was first added last year). Hopefully with some additional info we can diagnose the source of this problem!

**Comment by RomanTheCube** [comment]
That is the strange part @jamessimone - This is a fresh install!
I have DLRS installed but having checked the apex classes I don't believe there are any conflicts there as no such RollupTests class exists...

**Comment by jamessimone** [comment]
@RomanTheCube do you have any validation rules on Opportunity that might prevent the opportunities in those two tests from being inserted? Additionally - those tests run on the CloseDate field for the opportunity in question: is there any other automation in your org that might be updating the CloseDate in some strange way?

Those tests are pretty simple - it’s unusual that the update / delete tests surrounding that same behavior would pass and only the inserts would fail.

**Comment by RomanTheCube** [comment]
Looks like you were correct - There was indeed automation linked to CloseDate field that I just disabled and was able to deploy successfully. Thankyou for the tip!

**Comment by jamessimone** [comment]
Makes sense - glad to hear it!
