### ISSUE TITLE
Too many query rows: 50001 when Recalculating

### ISSUE THREAD

**Issue by deckblad** [jamessimone/apex-rollup#215]
We're an old org with way too many large Campaigns with thousands of Leads looking up.

I've a simple count child->parent rollup from Lead to Campaign:

![image](https://user-images.githubusercontent.com/4379218/142299203-0be0a51f-cd19-41af-bf1b-d696957f152d.png)

When running Recalculate, even with a batch size of 1, I get this result: 

![image](https://user-images.githubusercontent.com/4379218/142299243-b841a585-9938-4896-ab3c-ab706d4dbd80.png)

I had chatted with @jamessimone via Discord and they said they already recognize the problem. I'll leave it to them to provide additional context here.

**Comment by jamessimone** [comment]
Hey David, thanks for submitting this! This is an issue with full recalcs only, due to pulling back too many child records. If I need any further info on this one, I will let you know!

**Comment by jamessimone** [comment]
@deckblad promoting a potential fix for this at the moment. I say "potential" because the actual issue is nearly impossible to test for in my own sandbox, with its limited data volume. We may need to do another round of revisions depending on what happens - but I will work with you at every step of the way to ensure this issue is brought to resolution!

**Comment by jamessimone** [comment]
Closing this for the moment - please feel free to re-open if this is still an issue, otherwise the fix from #216 worked
