### ISSUE TITLE
class java.math.BigDecimal cannot be cast to class java.lang.Integer

### ISSUE THREAD

**Issue by grekker** [jamessimone/apex-rollup#229]
Looks like #212 is still an issue. I'm running version 1.3.22 (I first installed the package with 1.3.15, and was getting the error on that version as well).

"System.UnexpectedException: class java.math.BigDecimal cannot be cast to class java.lang.Integer (java.math.BigDecimal and java.lang.Integer are in module java.base of loader 'bootstrap')"

This is thrown by line 614 of RollupAsyncProcessor:

this.getDML().doUpdate(updatedLookupRecords.values());

Here is the stack trace when it happens during a Batch Apex execute method:

Class.RollupAsyncProcessor.process: line 614, column 1
Class.RollupAsyncProcessor.runCalc: line 315, column 1
Class.Rollup.runFromTrigger: line 1342, column 1

Here is the stack trace when it occurs when editing a single record:

Class.RollupAsyncProcessor.process: line 614, column 1
Class.RollupAsyncProcessor.QueueableProcessor.execute: line 453, column 1

Let me know what other info would be useful for debugging.

**Comment by jamessimone** [comment]
@grekker happy to help address this situation. What kind of rollup (`COUNT`, `COUNT_DISTINCT`, etc …) are you configuring, and what are the field types (Number 18,0, for instance) that you are using between the calc item and the parent your are rolling up to?

I’m sorry to hear this is still an issue for you but with a bit more information I’m confident I’ll be able to fix the issue for you — and hopefully permanently this time. I was able to get a lot more insight when it came to #212 since it first came up.


Lastly, if you _are_ able to send a single record log with the `Org_Defaults` rollup control’s `Is Rollup Logging Enabled` flag enabled, that would be great; otherwise, I will follow up here after getting your initial response with other info I’ll need. I am on a short schedule this week, but once I have more info from you, I will work to resolve this ASAP as my availability increases!
