### ISSUE TITLE
Call Rollups from the parent object

### ISSUE THREAD

**Issue by solo-1234** [jamessimone/apex-rollup#25]
Hi! I'm thinking it would be useful to have the ability to call rollups (either via trigger or flow) from the parent object. One example would be for scheduled flows running on the parent (which is cleaner than running on the child).

Thanks!

**Comment by solo-1234** [comment]
Here's another use case:
I have a trigger/class that runs on parent records and creates a bunch of child records. When it's done, I'd like to roll them up to the parent, and it would be pretty neat to do that right inside my code.

**Comment by jamessimone** [comment]
@solo-1234 I’m nearly done with this feature, though I’ve been sidetracked in releasing it due to #42 that you reported! Question on what you just said - when you say “when it’s done,” you’re referring to the insert of the children records, yes?

also, since we are on the topic of Apex Triggers, are you doing this in a before or after update trigger context? Your answer there may well determine some functionality related to this implementation!

**Comment by solo-1234** [comment]
Both good news :)

Well, if this feature was implemented I'd skip the record edit flow and do that rollup here, so for me they are related :)

I'm referring to after inserting the child records, and this is done in an after-insert trigger (on the parent).

Thanks!

**Comment by jamessimone** [comment]
@solo-1234 if that's the case, I may get this feature finished up today and include a snippet in the Readme about the current issue (or limitation! it's all in the branding 😇) with Record-triggered flows also needing to employ a Get Records action until I can get some more guidance internally on what the actual root cause with #42 is.

**Comment by solo-1234** [comment]
That makes sense to me!

**Comment by solo-1234** [comment]
Thanks!

**Comment by jamessimone** [comment]
You are very welcome!
