### ISSUE TITLE
CPU Timeouts with large set of Rollups

### ISSUE THREAD

**Issue by melissajhansen** [jamessimone/apex-rollup#262]
Hey James, I think the underlying issue is already on your radar, per the TODO here: https://github.com/jamessimone/apex-rollup/blob/26c839763fa1ad35fb89de5ea4ab0de6c3768ed9/rollup/core/classes/RollupAsyncProcessor.cls#L931

But figured I'd flag that I am seeing CPU limits when I have a large number of rollups (~90) for a single object.  Debugging led me to that spot in the RollupAsyncProcessor so I'm guessing it's related to the issue you referenced in a code comment.  For now, I'm working with my client to winnow down the number of rollups, a good thing to do regardless, but I'm not sure where this is in the overall priorities.

Thx!

**Comment by jamessimone** [comment]
Hey @melissajhansen, thanks for submitting this. There are a few things I am planning to do to address this in the next release, with the TODO you highlighted being one of them. I don’t have a firm timeline on the next release, as I’d like to do a more rigorous round of testing on the changes I’m hoping to make, but I will keep you updated here on my progress, especially if there is any undue delay.

**Comment by melissajhansen** [comment]
Sounds good.  Thanks @jamessimone !

**Comment by jamessimone** [comment]
@melissajhansen I was able to do some benchmarking today and feel confident that the changes I'll be releasing will at least _help_ - at best, get rid of entirely - the CPU timeout issues you've been experiencing. I'll be hopeful to hear good news from you, here, but please re-open this in the event that #266 does not end up fixing these issues entirely. We may need to do some benchmarking via logging in order to address further, in that case. Either way, looking forward to hearing from you!

**Comment by melissajhansen** [comment]
Thanks @jamessimone !  I will do some re-testing and let you know!

**Comment by jamessimone** [comment]
Sounds good!
