### ISSUE TITLE
Question: Multiple rollups on same object using flow

### ISSUE THREAD

**Issue by cybotjr** [jamessimone/apex-rollup#38]
Hello Again, Thank you for the quick fix on the previous issue!

I was using the apex .batch method and realized I also wanted to use FullRecalculationDefaultNumberValue__c = 0 with it, but it defaults to using whatever is in the target field. I know I can use a flow instead for this, but I am wondering how to go about rolling up multiple fields to an object without running into a limit? If I chain a bunch of Actions in the flow for each rollup, I assume each runs on its own, using SQL + DML in each? If that's the case, it might be good to allow decoupling the final DML in the flow as an option, collecting the records after each Action, and doing the final Update all at once via a Flow Update node.

Also, would I need to create an Action node per rollup context (INSERT / UPSERT / UPDATE / DELETE) or one for UPSERT & Another for DELETE, to cover all scenarios of the rollup?

**Comment by jamessimone** [comment]
I was wondering when this would happen - the slight deviation between the arguments supplied in the static methods versus what’s possible in Flow / by CMDT.

My issue with the way that Flow currently allows Invocables is that what appears to be bulkified at the Apex level is only truly bulkified for a single call to an action wit in the Flow runtime. I agree with your assessment that decoupling the final DML till called by Flow is the ultimate solution, but ideally I’d like to fix this by actually giving somebody using Flow the ability to pass the arguments the way that they’re presented in Apex (eg: a list of Flow Inputs). This is because most of the “action” in Rollup is async, and as such there isn’t a safe, multi-threaded, context available to each operation. In the short term, however, because the operations are async, you shouldn’t have to worry about SOQL / DML limits being exceeded in your flow. One of my Flow power users is currently rolling up over 50 fields in a single flow, and she hasn’t run into any governor limit issues.

The action node context question depends on what you’re doing. If your flow is auto-launched, odds are you only need one context; it’s only an update operation if you’re manipulating the calculation items in memory within the flow. For a record triggered flow, unfortunately right now since the types of record triggered flows are unique (eg: one flow for after update, one for after insert), that’s when you would use insert update delete. There is no upsert context at this moment - are you doing upserts?

**Comment by jamessimone** [comment]
(Commenting as is because my phone is about to die, will follow up later!)

**Comment by cybotjr** [comment]
Thanks for the response James.

I am not using upserts, just saw that in the flow documentation "Rollup Context - INSERT / UPSERT / UPDATE / DELETE", and figured UPSERT would cover whenever a record is updated/inserted.

Glad to hear it should run fine, when I'm done it will be close to 50 rollups as well.

Currently playing with the flow, haven't gotten it to work though. I used a trigger and that worked, but I wanted to use Full Recalculation for a few roll ups.
This is what I have on the creation or updation of a Task, the Calc Item Rollup Field is a formula returning 1 if the task has subject = "Outreach". {!Tasks} is the collection variable I used in the assignment 'Tasks ADD {!record}'. I set UPDATE assuming that means I am updating the Parent, Case Object here. I am not getting any Flow Interview error emails, so not sure what i may be missing. I'm looking at the {!Tasks} list as the potential culprit, maybe I am assigning it incorrectly.

![Screen Shot 2021-02-21 at 5 53 32 PM](https://user-images.githubusercontent.com/29462526/108641542-bad96a00-746d-11eb-98b4-a0998bcfc006.png)

![Screen Shot 2021-02-21 at 5 52 42 PM](https://user-images.githubusercontent.com/29462526/108641502-9aa9ab00-746d-11eb-84dd-61abc218dcfb.png)


![Screen Shot 2021-02-21 at 5 46 33 PM](https://user-images.githubusercontent.com/29462526/108641325-be202600-746c-11eb-80f2-a3f21475671a.png)

**Comment by cybotjr** [comment]
I figured it out. The context mean, the context from the child record. In my case INSERT whenever a task is created. I thought it was the operation being done on the target 🤦 .

**Comment by jamessimone** [comment]
@cybotjr yes, as you said, that operation is an INSERT. The "update" case, at the moment, would only be applicable if the records were modified after Get Records in the flow, but before the Apex action was called, and the update involved changing the values present for the calculation item's rollup field. Otherwise, from the perspective of Flow, UPDATE is reserved for the record-triggered flows.

As for the periodic full recalc - that's really up to you! It depends on how much trust/permissions you give your users; I'm used to it being the case that the fields on the parent are permissioned as read-only for anything other than admins, but if you're worried about the values being overwritten accidentally, a scheduled job makes sense.

Let me know if that helps, and thanks again for providing feedback!

**Comment by cybotjr** [comment]
No problem! 

The tool is great so far! It might be cool to have a multi-rollup option, where you map fields SObjectFields from child to parent, for the same types of rollups, if they are all SUMs for example. Or Map the Child Field to Parent Field and Operation, since the rest of the inputs would be the same.

**Comment by jamessimone** [comment]
@cybotjr I love that idea, but I'll have to chew on it for a bit. It's a little tricky without better "mapping" structures in Flow; I've done some hacky things in the past for fields like this (comma separated, or using `=>` fat arrow syntax to map things), but it's been a while since I investigated using Apex types as the basis for variables in Flow, and I need to refresh my memory on whether or not that would work for what you're describing.

**Comment by jamessimone** [comment]
@cybotjr also - to return to one of the points you raised initially, I need to add the default recalculation values as arguments to the static methods exposed in Apex. Thank you for pointing that out.

**Comment by jamessimone** [comment]
@cybotjr the static Apex methods for using default values have now been added in #39 and released. Sorry for the oversight in not providing those overloads initially

**Comment by cybotjr** [comment]
Awesome @jamessimone ! Thanks for that !

**Comment by jamessimone** [comment]
@cybotjr I started working on decoupling the loading of Rollups from the final “start” to the rollup operation as part of my work on #26. I expect to wrap up both of these features tomorrow!

**Comment by jamessimone** [comment]
@cybotjr deferring rollups in flow is now possible in the latest release - let me know what you think!

**Comment by cybotjr** [comment]
@jamessimone That's amazing! Will upgrade and give it a try this weekend. Will let you know how it goes.
