### ISSUE TITLE
Rollup behaving funny on Developer Scratch Org (not taking into account maximum stack depth)

### ISSUE THREAD

**Issue by dschibster** [jamessimone/apex-rollup#395]
Hi James!

Does the `DeferredFullRecalcProcessor` take into account the Rollup Controls of the given Rollup, if only one is taken?
I was preparing a demo for a Architect Group meeting tomorrow, and wanted to run the full recalc to test a Rollup I created. To my surprise, the result was 4 times the expected result - But probably because the maximum stack depth was reached so the calculation never concluded. 😄 

I checked and created a new Rollup Control and all, but it didn't matter, it still ran as a Queueable and it still broke even though the amount of records to roll up amounted to something like ... 4. 😄 

Here's a repo with the Rollup Record and the situtation frozen. The only thing I did was create an Account with a won Opp, then create the Parent Account after the fact, then tried the Recalculation Button for CMDTs in your LWC.

https://github.com/dschibster/architectgroupdus-20221215-demo/tree/testing-grounds-for-james

For the time being I will be using the common workaround to create an Enterprise Scratch Org. Hope it doesn't come up there too. 😄

**Comment by jamessimone** [comment]
I will take a look, I made a recent change to the requeuing behavior for
dev orgs, and that may have broken something unfortunately. Thank you so
much for providing the repo - that makes a huge difference!

**Comment by dschibster** [comment]
Thanks!
Going into it a little further, it seems like it only has this problem when it realizes that it needs to perform an update. I manually corrected the Rollup on my Enterprise Scratch Org (which, wouldn't you know, is actually subject to the same Async Apex Limits), and everything went without a hitch (because nothing happened, I wager)

When I reset the value to 0, it went crazy again. :) So in essence I think both master and the branch I left open for you should behave the same in this case.

**Comment by jamessimone** [comment]
@dschibster I didn't get the chance to look into this today but I am planning to set aside time tomorrow for it.

**Comment by jamessimone** [comment]
@dschibster I want to make sure I understand the order of operations that's going on here. Let me bring you up to speed on what I did:

* Created a Closed Won opportunity and associated it with one of the standard accounts included with a scratch org (in this case, I went with "Sample Account For Entitlements", since it's one of the ones that has no opps by default)
* Observed that the Amount field rollup up successfully to the Overall Revenue field on that account
* Made a new account, "Parent Account", updated the Parent Account lookup on "Sample Account For Entitlements" to "Parent Account" (observed that the Overall Revenue of Child Accounts" field was at this point already correct, but I cleared it out as well). I cleared this value out prior to the next step, just to be safe.
* Went to the full recalc app for rollups and selected Account on the CMDT "side" of the page, hit "Start Rollup"
* Observed that the Overall Revenue of Child Accounts field updated successfully again

Am I doing anything wrong or trying to reproduce the wrong steps here? Happy to schedule a call next week if that's more convenient to discuss, otherwise I will have time today and throughout the weekend to try to diagnose any issues.

**Comment by dschibster** [comment]
In essence you did the things that I did. The one thing that I was doing is clever me actually created the rollup setting after I created the parent account and linked it to the one with opps.

The rest is the same though. In my scratch Org, even with the rollup control set to what it was, I was running into maximum stack depth errors.

Happy to give you access to that one for you to see yourself. Not sure if I am able to enable thorough logging. :)

**Comment by jamessimone** [comment]
that would be great! It must be some subtle difference in our setups, I'd love to see what's going in there.

**Comment by jamessimone** [comment]
@dschibster good evening - I was able to track down the source of this issue. It was a bit subtle! The CMDT-driven flow defaults to the `Defer Processing` setting being true - it essentially requires another action (the "Process Deferred Rollups" one) to be added to the flow (alternatively, you can set `Defer Processing` in the optional flow variables to false.

When a rollup is deferred in Flow, it sits out there in the queue, waiting to fire - unfortunately, this interacts poorly with the Full Recalc process, which then attempted to kick the cached flow recalc off. This was causing lots of wheel spinning and, ultimately, the "Maximum stack depth has been reached" error. When I added the "Process Deferred Rollups" action to your flow, that fixed the issue. Let me know if you want to review this at all!

**Comment by dschibster** [comment]
Thanks a lot for taking a look. Makes a lot of sense! I actually did already have that Action in the final version of the RT-Flow that I was showcasing. So I unknowingly fixed the issue myself. Whoops. :)

**Comment by jamessimone** [comment]
All is well that ends well!
