### ISSUE TITLE
Error with flow rollup

### ISSUE THREAD

**Issue by solo-1234** [jamessimone/apex-rollup#42]
Hi! I'm getting an error with a rollup. When inserting records of the child object, I get:

`We can't save this record because the “Rollup Flow” process failed. Give your Salesforce admin these details. Unable to convert value '{...}' to Apex type SObject for Apex action RollupFlowBulkProcessor Variable recordsToRollup Error ID: 1509407456-129770 (-2081482679)`

Where the ... represents every field and value on the child record.

This is a rollup that previously worked fine. I tried switching to a flow calling CMDT rollup but I still get the same error.

Any idea what could be causing that? TY

**Comment by jamessimone** [comment]
@solo-1234 let me look into that and get back to you, just to confirm the “Records to Rollup” variable is pointing to a collection retrieved by Get Records or a collection established from a record triggered flow?

**Comment by solo-1234** [comment]
Thanks! This is passed in from a record triggered flow. It's triggering when children are inserted, so each flow interview is passing in a collection which contains one record, but a few are usually inserted at once. It also fails if I try to insert only one.

**Comment by jamessimone** [comment]
@solo-1234 this is bizarre. I hadn’t tested my record triggered flow in a while - I’ve been using auto launched flows with a Get Records action since they’re so much easier to debug at the moment. I was able to validate tonight that this isn’t a recent issue; I tested all kinds of recent iterations of Rollup and had this issue on the CMDT Invocable and the original one as well, and reactivating the original record triggered flow I used for the Readme screenshots also reproduced the issue.

which means ... it could be a Spring 21 issue. I had to shut down for the day before investigating that possibility. It could be any number of things, and I’m hopeful that between being able to actually investigate the gacks at work and testing, I’ll be able to iron out this issue soon.

I’m really sorry that this is happening. I should have more information on a fix in the next day or two.

**Comment by solo-1234** [comment]
It is really strange! Especially since it's not working now on records that it used to work on (and the issue started while I was testing something new, so at first I thought I broke it). Not sure if it's related to Spring, or maybe a patch...  Seems like it stopped working for me somewhere in between 2/22 and 2/25, which is after the Spring release. I don't know of a way to see when patches are delivered.

Thanks for all your work figuring this out! I'll stay tuned...

**Comment by solo-1234** [comment]
Okay as a workaround, I added in a Get Records to find the record with the Id of $Record.Id, and passed that to the action instead, and it seems to work fine! So I'll leave that in place until you figure this out (no rush!)

Thanks!

**Comment by jamessimone** [comment]
@solo-1234 très bizarre, as they say. I will continue to investigate and keep you updated on any progress - great thinking on the Get Records workaround for now!

**Comment by solo-1234** [comment]
Yep - thanks for your help!
