### ISSUE TITLE
Attempt to de-reference a null object when refreshing from flow

### ISSUE THREAD

**Issue by segdan** [jamessimone/apex-rollup#485]
Hi,

I'm facing a strange issue when rolling up in a refresh context from a flow. 

11:09:56.211 (2332211837)|FATAL_ERROR|System.NullPointerException: Attempt to de-reference a null object

Class.RollupCalculator.DecimalRollupCalculator.handleSumOrCount: line 589, column 1
Class.RollupCalculator.performRollup: line 205, column 1
Class.RollupAsyncProcessor.getCalculator: line 1347, column 1
Class.RollupAsyncProcessor.getUpdatedLookupItemsByRollup: line 1250, column 1
Class.RollupAsyncProcessor.process: line 694, column 1
Class.RollupAsyncProcessor.performWork: line 350, column 1
Class.RollupAsyncProcessor.QueueableProcessor.execute: line 457, column 1

I checked the log file but I'm unable to determine which one is the null object referred, and apparently this error is blocking all the rollups from beign calculated. I'm on version 1.5.83. Please find the whole log file attached and let me know if anything else is needed to debug this problem. Thanks

[07L0D00000Gwj7lUAB.log](https://github.com/jamessimone/apex-rollup/files/12484893/07L0D00000Gwj7lUAB.log)

**Comment by segdan** [comment]
found the problem, one of the metadata records had a string default value instead of a decimal one. Now I have a different problem: when the rollup refresh is triggered by the flow, the rollups are not updated 90% of the times (strangely sometimes they are updated but I couldn't understand why), but if I use the recalculate rollups button it works everytime

**Comment by jamessimone** [comment]
Hey @segdan, happy to try to help. Prior to being able to speculate on what the issue is, would you be able to update the Org Default Rollup Control custom metadata record to enable Is Rollup Logging Enabled and generate a log file to upload here? The log should show what's going on. Typically, there will be three logs generated when you update a record with Apex rollup - one with Origin of Aura, which is the sync part of the process. Then there's a QueueableHandler / blank Origin log - that's the one that probably has the info we need to examine. There's _another_ log with the same origin as the second one; this is the RollupFinalizer and you don't need to include it. The aura and first of the two queueable logs would be very helpful though!

**Comment by segdan** [comment]
Hi @jamessimone , thanks for the quick feedback. Here are the two files, let me know if you need anything else. These logs were generated in one of the attempts where the rollups didn't update. If this can help, I'm specifically checking the Total_ARR_Override__c field on OpportunityLineItem, which should have been updated to 211000, and instead has the old value of 263000. I guess also the other rollups are not updated, but this one for sure is not.
[07L0D00000GwjnPUAR.log](https://github.com/jamessimone/apex-rollup/files/12485544/07L0D00000GwjnPUAR.log)
[07L0D00000GwknTUAR.log](https://github.com/jamessimone/apex-rollup/files/12485548/07L0D00000GwknTUAR.log)

**Comment by jamessimone** [comment]
Thank you! I will have a look.
