### ISSUE TITLE
Add custom hierarchy setting for enabling/disabling rollup 

### ISSUE THREAD

**Issue by jongpie** [jamessimone/apex-rollup#58]
In some situations, like data migration, it'd be useful to be able to temporarily disable rollups from executing - a new custom hierarchy setting with a checkbox fields seems like the cleanest approach & would let you disable it just for certain users, profiles and/or the entire org.

**Comment by jamessimone** [comment]
I agree - this may also help with installation; some people have issues installing due to the fact that the tests operate on some objects (like Opp / Account) which are already common sources of automation. Having a custom setting to enable / disable will definitely help with that, though it's a shame CMDT don't currently offer the same hierarchical support that custom settings do, as I was really hoping for `RollupControl__mdt` to be the single source of truth for this.

**Comment by jongpie** [comment]
Yeah, I wasn't thinking about how it would help with tests, but that's definitely another good benefit.

If you want to stick with just CMDT instead of custom settings, you can somewhat mimic that with custom fields & validation rules. Here are some screenshots of an unfinished feature for logger that did this - you could do something similar in `RollupControl__mdt`

Org level
![image](https://user-images.githubusercontent.com/1267157/111811003-d9c3f400-8893-11eb-8d60-ea8562de0d95.png)

Profile level
![image](https://user-images.githubusercontent.com/1267157/111811041-e1839880-8893-11eb-9939-f2cbf9d21012.png)

User level
![image](https://user-images.githubusercontent.com/1267157/111811087-eba59700-8893-11eb-9cd8-f3e71e105f9b.png)

**Comment by jamessimone** [comment]
Ah interesting - that's a hot take! OK, plenty of good food for thought here. Thanks!
