### ISSUE TITLE
Hitting SOQL Too Many Query Rows with AVERAGE

### ISSUE THREAD

**Issue by PhilTerz** [jamessimone/apex-rollup#589]
Over a large dataset, AVERAGE is requerying in each batch chunk handler. I can see each handler's log does a query that fails after returning 50,001 rows.

**Comment by jamessimone** [comment]
Thanks for submitting this! I should be able to start working on this today or tomorrow.

**Comment by jamessimone** [comment]
@PhilTerz apologies, I've had less time to get the fix for this out there than I had hoped for. I have things working for AVERAGE but I expect to have more time in the next day or two to sew up a few other operations that suffer from a similar issue. You can expect this fix to be released in the next few days!
