### ISSUE TITLE
Discrepancy btwn Rollup Context and "Trigger the Flow When"

### ISSUE THREAD

**Issue by rygramer** [jamessimone/apex-rollup#77]
Hey James,

Been looking forward to implementing this since you released it in Dec; thanks for the solid work.

[I got hung up on your screenshot comment:](https://github.com/jamessimone/apex-rollup/blob/main/media/example-perform-rollup-action.png). Recorded a quick video explaining what was going on. Am I missing something? https://share.vidyard.com/watch/RQEwPYY9BmsTrFvtNKrATP

**Comment by jamessimone** [comment]
Hey @rygramer - good to see you here man, hope your work at Kicksaw is going well. I edited your comment a bit since the link was broken - hope you don't mind. I will have the chance to take a look at the video in a bit, apologies for the delay.

**Comment by rygramer** [comment]
Thanks James. No rush at all; 0 functional issues, it’s working great. Just
a documentation question.

**Comment by jamessimone** [comment]
@rygramer ah, I see what you mean. I should refine the comment in that screenshot, absolutely. `UPSERT` for a flow isn't really valid; I may even take that option away. It was working fine for you with `INSERT` because then `Rollup` doesn't try to do a diff; it doesn't work with `UPSERT` or `UPDATE` because those are _really_ only valid if you've modified the records _in the flow_ prior to rolling them up but after using a `Get Records` element (or the direct records themselves, in a record-triggered flow where you're rolling up the actual records that triggered the flow). I will update the documentation to make that point clear in the upcoming `v1.2.9` release. Thank you for raising this issue!

**Comment by rygramer** [comment]
Oh gotcha, that’s good to know. Thanks for the clarification. You da man

**Comment by jamessimone** [comment]
@rygramer I wanted to be sure you'd seen the updated rollup version, which (as best as possible) restores UPSERT as a possibility. UPSERT won't work for records being processed through record triggered flows with backfilled `CreatedDate` fields, but otherwise will allow for the use of `when a record is created or updated` instead of needing two separate flows for that.

**Comment by rygramer** [comment]
Great! Thanks so much James. I'll take a peek

**Comment by rygramer** [comment]
@jamessimone had some trouble upgrading. Once I got the newest version installed, it's working great.

```
lwc/rollupForceRecalculation/rollupForceRecalculation.js-meta.xml: You can’t remove the following public properties: rollupData,rollupMetadataOptions,selectedMetadata, because the component is part of a managed package.
rollupForceRecalculation: lwc/rollupForceRecalculation/rollupForceRecalculation.js-meta.xml: You can’t remove the following public properties: rollupData,rollupMetadataOptions,selectedMetadata, because the component is part of a managed package.
```

**Comment by jamessimone** [comment]
Interesting - what was your path to resolution? Sorry about that! I had to
change the API behind that component because all of those properties were
getting to be a bit much to pass around. It won't change again.

**Comment by rygramer** [comment]
Uninstalled and reinstalled. The UPSERT modification is a game changer.
Great work
